#include <pch.h>
#include "dumper.h"
#include "game.h"


static const std::unordered_map<int, std::string> cvarTypeMap =
{
	{StarCitizen::Enums::CVARTYPE_INT, "int"},
	{StarCitizen::Enums::CVARTYPE_FLOAT, "float"},
	{StarCitizen::Enums::CVARTYPE_INT64, "int64"},
	{StarCitizen::Enums::CVARTYPE_STRING, "string"},
};
void DumpCVARS()
{
	using namespace StarCitizen;
	const __int64& dwModuleBase = __int64(GetModuleHandle(0));

	// Define path for the output file
	const std::filesystem::path logpath = std::filesystem::current_path() / "dump_cvars.txt";

	// Delete the old file directly if it exists
	if (std::filesystem::exists(logpath))
	{
		std::filesystem::remove(logpath);
	}

	// Open file for appending
	std::ofstream varsFile(logpath, std::ios_base::app);
	if (!varsFile.is_open())
	{
		std::cerr << "Failed to open dump_cvars.txt for writing.\n";
		return;
	}

	varsFile << "// STAR CITIZEN CONSOLE VARIABLES\n// Generated by: NightFyre\n// Count: " << StarCitizen::Hooks::vars::vConsoleVariables.size() << "\n\n";

	for (const auto& cvar : StarCitizen::Hooks::vars::vConsoleVariables)
	{
		if (!cvar.Description || !cvar.Name)
			continue;

		auto it = cvarTypeMap.find(cvar.type);
		if (it == cvarTypeMap.end())
			continue;


		//	[type, value] Name
		//	Description
		//	/n
		//	/n

		varsFile << "[" << it->second << "][";				//	type

		if (cvar.type == Enums::CVARTYPE_INT)
			varsFile << *(int*)cvar.flagPTR << "] ";			//	value
		else if (cvar.type == Enums::CVARTYPE_FLOAT)
			varsFile << *(float*)cvar.flagPTR << "] ";			//	value
		else
			varsFile << "] ";

		varsFile << cvar.Name << "\n"						//	name
			<< cvar.Description << "\n\n";						//	description
	}
	varsFile.close();
}

void DumpCommands()
{
	using namespace StarCitizen;
	const __int64& dwModuleBase = __int64(GetModuleHandle(0));

	// Define path for the output file
	const std::filesystem::path logpath = std::filesystem::current_path() / "dump_commands.txt";

	// Delete the old file directly if it exists
	if (std::filesystem::exists(logpath))
	{
		std::filesystem::remove(logpath);
	}

	// Open file for appending
	std::ofstream commandsFile(logpath, std::ios_base::app);
	if (!commandsFile.is_open())
	{
		std::cerr << "Failed to open dump_commands.txt for writing.\n";
		return;
	}

	commandsFile << "// STAR CITIZEN COMMANDS\n// Generated by: NightFyre\n// Count: " << StarCitizen::Hooks::vars::vConsoleCommands.size() << "\n\n";

	for (const auto& command : StarCitizen::Hooks::vars::vConsoleCommands)
	{
		if (!command.fnPtr || !command.Description || !command.Name)
			continue;

		//	[addr, flags] Name
		//	Description
		//	/n
		//	/n
		commandsFile << "[0x" << std::hex << (__int64(command.fnPtr) - dwModuleBase)	//	address 
			<< ", 0x" << command.flags << std::dec << "] "								//	flags
			<< command.Name << "\n"														//	name
			<< command.Description << "\n\n";											//	description
	}
	commandsFile.close();
}

// Predefined field type mappings to strings for easy access
static const std::unordered_map<int, std::string> typeMap =
{
	{StarCitizen::Enums::FIELDTYPE_BOOL, "bool"},
	{StarCitizen::Enums::FIELDTYPE_UINT32, "__int32"},
	{StarCitizen::Enums::FIELDTYPE_FLOAT, "float"},
	{StarCitizen::Enums::FIELDTYPE_CONSTCHAR_PTR, "char*"}
};
static constexpr size_t MAX_FIELDS = 256;
static StarCitizen::Structs::SDataField* outFields[MAX_FIELDS];				//	
void DumpStructs()
{
	using namespace StarCitizen;

	const auto& pEnv = gEnv;
	if (!pEnv)
	{
		printf("Failed to get gEnv pointer.\n");
		return;
	}

	const auto& pData = pEnv->pDataCore;
	if (!pData)
	{
		printf("Failed to get pDataCore pointer.\n");
		return;
	}

	auto GetStructDataFields = [pData](std::string structName, StarCitizen::Structs::SDataField** outBuffer) -> __int64
		{
			return CallVFunction<__int64>(pData, 11, structName.c_str(), outBuffer, 1);
		};

	// Define path for the output file
	const std::filesystem::path logpath = std::filesystem::current_path() / "dump_structs.h";

	// Delete the old file directly if it exists
	if (std::filesystem::exists(logpath))
	{
		std::filesystem::remove(logpath);
	}

	// Open file for appending
	std::ofstream offsetsFile(logpath, std::ios_base::app);
	if (!offsetsFile.is_open())
	{
		std::cerr << "Failed to open dump_structs.h for writing.\n";
		return;
	}

	offsetsFile << "// STAR CITIZEN STRUCTURES\n//\tGenerated by: NightFyre\n//\tCount: " << StarCitizen::Hooks::vars::vStructNames.size() << "\n\n";


	//	
	for (const auto& structName : StarCitizen::Hooks::vars::vStructNames)
	{
		auto fieldNum = GetStructDataFields(structName, outFields);
		if (!fieldNum || fieldNum > MAX_FIELDS)
		{
			std::cerr << "// [!] FAILED TO FIND STRUCT [" << structName << "]\n\n";
			continue;
		}

		offsetsFile << "struct " << structName << "\n{\n";

		DWORD currentOffset = 0;
		DWORD structEnd = 0;
		bool hasFields = false;

		for (int j = 0; j < fieldNum; ++j)
		{
			if (!outFields[j])
				continue;

			auto dataField = outFields[j];
			hasFields = true;

			// Check if padding is needed before this field
			if (dataField->fieldOffset > currentOffset)
			{
				DWORD paddingSize = dataField->fieldOffset - currentOffset;
				offsetsFile << "\tunsigned char pad_" << std::hex << currentOffset
					<< "[0x" << paddingSize << "]; // 0x" << currentOffset << "\n";
				currentOffset += paddingSize;
			}

			// Get the field type
			auto it = typeMap.find(dataField->fieldType);
			if (it != typeMap.end())
			{
				offsetsFile << "\t" << it->second << "\t" << dataField->fieldName
					<< "; // 0x" << std::hex << dataField->fieldOffset << std::dec << "\n";
			}
			else
			{
				offsetsFile << "\tunsigned char pad_" << std::hex << dataField->fieldOffset
					<< "[0x" << dataField->fieldSize << "]; // 0x" << dataField->fieldOffset
					<< " | Name: " << dataField->fieldName << " | Size: 0x"
					<< dataField->fieldSize << " | Type: 0x" << dataField->fieldType << "\n";
			}

			currentOffset = dataField->fieldOffset + dataField->fieldSize;
			structEnd = std::max(structEnd, currentOffset);

			outFields[j] = nullptr;
		}

		// Check if there's remaining padding at the end
		if (structEnd > currentOffset)
		{
			offsetsFile << "\tunsigned char pad_" << std::hex << currentOffset
				<< "[0x" << (structEnd - currentOffset) << "];\n";
		}

		if (!hasFields)
		{
			offsetsFile << "\t// [!] FAILED TO DUMP [" << structName << "]\n";
		}

		offsetsFile << "}; // Size: 0x" << std::hex << structEnd << std::dec << "\n\n";


		//	CLEAR FIELDS BUFFER
		memset(outFields, 0, sizeof(outFields));
	}

	offsetsFile.close();
}

void DumpClasses()
{
	using namespace StarCitizen;

	//	get class names
	std::vector<const char*> g_classNames(StarCitizen::Hooks::vars::class_names, StarCitizen::Hooks::vars::class_names + StarCitizen::Hooks::vars::class_names_count);
	if (g_classNames.empty())
	{
		printf("Failed to get class names.\n");
		return;
	}

	// Define path for the output file
	const std::filesystem::path logpath = std::filesystem::current_path() / "dump_entity_class_names.txt";

	// Delete the old file directly if it exists
	if (std::filesystem::exists(logpath))
	{
		std::filesystem::remove(logpath);
	}

	// Open file for appending
	std::ofstream namesFile(logpath, std::ios_base::app);
	if (!namesFile.is_open())
	{
		std::cerr << "Failed to open dump_entity_class_names.txt for writing.\n";
		return;
	}

	namesFile << "// STAR CITIZEN ENTITY CLASS NAMES\n// Generated by: NightFyre\n// Count: " << g_classNames.size() << "\n\n";

	//	std::sort(g_classNames.begin(), g_classNames.end(),
	//		[](const char* a, const char* b) {
	//			return std::strcmp(a, b) < 0;
	//		});

	DWORD index = 0;
	for (const auto& name : g_classNames)
	{
		if (!name)
			continue;

		namesFile << "[" << index << "] " << name << "\n";
		index++;
	}

	namesFile.close();
}
